language: php

services:
  - mysql

addons:
  apt:
    packages:
      - libnotify4

php:
  - 5.5
  - 5.6

before_install:
  - openssl aes-256-cbc -K $encrypted_0a0f4332d45b_key -iv $encrypted_0a0f4332d45b_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
  - rm composer.lock
  - composer self-update
  - npm -g install npm@3.5.1

install:
  - composer install
  - npm install

before_script:
  - mysql -e 'CREATE DATABASE `Traveling-Children-Project_Staging`'

script:
  - gulp
  - php artisan --env=staging --force migrate --seed

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_key
  - ssh-add .travis/deploy_key
  - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  - git remote add staging alexander@beta.travelingchildrenproject.com:/var/www/Staging/.git
  - git push staging master --force
