language: php

services:
  - mysql

php:
  - 5.5
  - 5.6

before_install:
  - rm composer.lock
  - composer self-update
  - npm -g install npm@3.5.1
  - apt-get update
  - apt-get install libnotify-bin

install:
  - composer install
  - npm install

before_script:
  - mysql -e 'CREATE DATABASE `Traveling-Children-Project_Test`'

script:
  - gulp
  - php artisan --env=staging --force migrate --seed
