language: php

services:
  - mysql

php:
  - 5.5
  - 5.6

before_install:
  - rm composer.lock
  - composer self-update
  - npm -g install npm@3.5.1

install:
  - composer install
  - npm install

before_script:
  - mysql -e 'CREATE DATABASE `Traveling-Children-Project_Test`'

script:
  - gulp
  - php artisan --env=staging --force migrate --seed

# Uncomment this to deploy to production
# at http://travelingchildrenproject.com/
# after a successful build
#
# after_success:
#   - git remote add production http://beta.travelingchildrenproject.com/
#   - git push production master
