language: php

services:
  - mysql

addons:
  apt:
    packages:
      - libnotify4

php:
  - 5.5
  - 5.6

before_install:
  - rm composer.lock
  - composer self-update
  - npm -g install npm@3.5.1

install:
  - composer install
  - npm install

before_script:
  - mysql -e 'CREATE DATABASE `Traveling-Children-Project_Staging`'

script:
  - gulp
  - php artisan --env=staging --force migrate --seed
