language: php

services:
  - mysql

php:
  - 5.5
  - 5.6

install:
  - rm composer.lock
  - composer self-update
  - composer install
  - npm -g install npm@next
  - npm install

before_script:
  - mysql -e 'CREATE DATABASE `Traveling-Children-Project_Test`'

script:
  - gulp
  - php artisan --env=staging --force migrate:refresh --seed
