language: php

php:
  - 5.5
  - 5.6

install:
  - rm composer.lock
  - composer self-update
  - composer install
  - npm -g install npm@next
  - npm install
  - gulp

script: php artisan migrate:refresh --seed --force
