language: php

services:
  - mysql

php:
  - 5.5
  - 5.6

before_install:
  - rm composer.lock
  - composer self-update
  - npm -g install npm@3.5.1

install:
  - composer install
  - npm install

before_script:
  - mysql -e 'CREATE DATABASE `Traveling-Children-Project_Test`'

script:
  - gulp
  - php artisan --env=staging --force migrate --seed

# Uncomment this to deploy to production
# at http://travelingchildrenproject.com/
# after a successful build
#
after_success:
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - git remote add production alexander@travelingchildrenproject.com:/var/www/Staging/.git
  - git push production master
