language: php

php:
  - 5.5
  - 5.6

install:
  - rm composer.lock
  - php5dismod xdebug
  - composer self-update
  - composer install
  - npm uninstall `ls -1 node_modules | tr '/\n' ' '`
  - npm install
  - gulp

script: php artisan -n migrate:refresh --seed
